import os
import gradio as gr

from langchain.chat_models import QianfanChatEndpoint
from langchain.schema.messages import HumanMessage

# 设置环境变量
os.environ["QIANFAN_AK"] = "wLRppEb0pBay9jZmDyZeG0Zk"
os.environ["QIANFAN_SK"] = "bzqLAMI57mtMttrS54O0ycpBaz8Ggdsf"

# 初始化模型
chatBloom = QianfanChatEndpoint(
    streaming=True,
    model="ERNIE-Bot",
)

def create_poem(question):
    """
    Prompts the model to create a modern poem based on the input sentence.
    """
    poetry_prompt = f"Create a modern poem inspired by the following sentence: '{question}'"
    response = chatBloom([HumanMessage(content=poetry_prompt)])
    return response[0].content if response else "No response generated."

# 创建 Gradio 界面
iface = gr.Interface(
    fn=create_poem,
    inputs=gr.components.Textbox(lines=2, placeholder="Enter a sentence to inspire a poem..."),
    outputs="text",
    title="Modern Poetry Generator",
    description="Enter a sentence to inspire a modern poem generated by AI."
)

# 启动界面
iface.launch()
